#!/usr/bin/env python3

import sys
from rqt_gui.main import Main

def add_arguments(parser):
    group = parser.add_argument_group('Options for bootcamp2_gui plugin')
    group.add_argument('topic', nargs='?', help='The topic name to subscribe to')

main = Main()
sys.exit(main.main(
    sys.argv, 
    standalone='bootcamp2_gui/bootcamp2Plugin',
    plugin_argument_provider=add_arguments))
